package client;

import javax.xml.bind.DatatypeConverter;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.math.BigInteger;
import java.net.URL;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Base64;

public class MD5 {
    public static String getMd5(String input) {
        try {

            MessageDigest md = MessageDigest.getInstance("MD5");

            byte[] messageDigest = md.digest(input.getBytes());

            BigInteger no = new BigInteger(1, messageDigest);

            String hashtext = no.toString(16);
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    public static String Decrypt(String md5_hash) throws Exception {

        MessageDigest digest = MessageDigest.getInstance("MD5"); // not thread-safe, create instance for each thread
        byte[] result = digest.digest(md5_hash.getBytes()); // get MD5 hash array, could contain negative
        String hex = DatatypeConverter.printHexBinary(result).toLowerCase();
        return hex;
    }

    // Driver code
    public static void main(String args[]) throws Exception {
        String s = "GeeksForGeeks";
        System.out.println("Your HashCode Generated by MD5 is: " + getMd5(s));
        System.out.println(Decrypt(getMd5(s)));
    }
}
